.github/workflows/ISSUE_TEMPLATE/ticket-issue-template.md
.github/workflows/pylint.yml
.github/workflows/pytest.yml
.gitignore

Rob repo structure

---

.github/workflows/pylint.yml

I have modified the workflows which pointed to folders that don not exist and therefore made them fail.
Closes #14.

Updated pylint and pytest workflows

---

.gitignore
terraform/database_creation.tf
terraform/outputs.tf
terraform/variables.tf

I have just completed the Terraform code that is needed to create the Postgres RDS database that will appear on AWS which will contain all of the data for our system on games.
I have created and connected to the following:
- AWS subnet for C15 (chose public as it is necessary)
- Created a new security group for our database
- Made an ingress and egress rule for the database to work with Postgres on port 5432
- Made the database instance for "games_tracker" which will hold all information
Closes #12

Completed the Terraform and made the Postgres RDS database

---

database/schema.sql

Changed the value of:
- Platform_id
- Platform_score
- Platform_price
From being able to be NULL to NOT NULL

Changed the null status in the game platform assignment table

---

terraform/steam_etl_pipeline.tf
terraform/variables.tf

I have created the code in a .tf file that will create all of the AWS resources needed for the ETL pipeline. These are:
- Three ECRs and their images for a Steam, Epic and GOG pipeline script that will extract game information, transform it to match the requirements of our database and load it in successfully
- IAM roles and policies for both the Lambda Functions and the Step Function
- The three Lambda Functions for each PC platform of Steam, Epic and GOG
- Cloudwatch Logs for the Step Function
- The Step Function that will call all three Lambda Functions sequentially
- IAM role for the Scheduler
- An EventBridge Scheduler that will run the Step Function daily
Closes ticket #35

Completed the Terraform code for all AWS resources needed for the ETL pipeline

---

pipeline/requirements.txt
pipeline/test_transform.py
pipeline/transform.py

I have taken your comments on the last pull and made changes listed here:
- Bigger testing suite now at 94% coverage, including testing for all new features.
- No longer removes all tags if one is invalid, removes it in formatting leaving only the correct tags.
- Same is true for genres, publishers and developers (all the list-based values).
- Added a global variable DAYS_BEFORE_TODAY_THAT_WILL_BE_ACCEPTED (name open to change) which when changed will allow for games released between today - DAYS_BEFORE_TODAY_THAT_WILL_BE_ACCEPTED days and today (so we can seed with some historical data)
- Only requirements for data now is that is has a title, a price (even if that price is 0), some genres and that it was released in the acceptable window
- Removed superfluous function I had added to pull …

Candice - Merge refactored steam transform script into main

---

pipeline/extract_epic.py

A ToDo for this is getting information on age rating and user reviews.
Should close #22

extracts games from API

---

pipeline/extract_steam.py
pipeline/test_extract.py

Closes #58 
- Added a larger testing suite that covers all init functions
- Broke up `scrape_newest()` by splitting a loop into `find_target_date()`
- Improves readibility
- Improves ease of testing
- Wrote a fairly comprehensive testing suite for the new function.
- Raises test coverage for extract to 64%
We still need to work on raising the test coverage but this is a start!
I'm taking a brief break from mocking now...

Candice - Merge extract tests & slightly refactored extract design.

---

pipeline/test_transform.py
pipeline/transform.py

Closes #57 
- Refactored transform to no longer use continue
- broke 4 functions into smaller ones
- Added testing for these new functions
- Fixed character limits on publisher, developer, tags and genres which were all set incorrectly!

Candice - Merge refactored transform, bug fix

---

README.md
cloud/README.md
dashboard/README.md
database/README.md
pipeline/README.md
pipeline/requirements.txt
terraform/README.md
terraform/variables.tf

Closes #60 
- Adds readmes to every folder
- Readmes include data specific to each folder
- Main readme has information for everything
This is only a first draft, will need to change as more files are added. @OfficialARM17 Please check over the terraform stuff in the main readme and move whatever you decide to change into the readme in the terraform folder when you have a moment!

Candice - Adding readme files

---

pipeline/test_transform.py
pipeline/transform.py

Changed default values as requested.

Candice - Minor changes to default values when erroneous data sent.

---

pipeline/epic_pipeline/README.md
pipeline/gog_pipeline/README.md
pipeline/steam_pipeline/README.md

I have refactored the pipeline README.md files so that they contain accurate information that is up-to-date and will grow with the additional work we need to do.
Additionally, I have also created the additional files we will need to make all three pipelines work and test for them correctly.
Closes ticket #82

Refactored the pipeline README.md files and more

---

.github/workflows/steam_pipeline_ECR.yml
pipeline/steam_pipeline/steam_pipeline_ECR.sh
pipeline/steam_pipeline/trigger_lambda_local.sh

I have created a shell script for deploying the ECR image that can be run locally. I have also created a workflow for automating the ECR image deployment.
Closes #73.

Rob steam pipeline image

---

dashboard/components.py
dashboard/main.py
dashboard/pages/subscribe.py
dashboard/requirements.txt

The initial dashboard layout setup and integration with AWS SNS. Closes #50 .
Next Steps:
- Filling the analytics page
- Adding existing genre set into subscription table as checklist

SNS dashboard integration and basic dashboard layout

---

database/schema.sql
test_terraform/steam_pipeline.tf
test_terraform/variables.tf

Just made a test folder for making Terraform resources at a time due to the iterative nature of the development
Also changed the schema and reset the database based on the fact that we want release date to be different by platform since games come out of different platforms on different days

Made a test folder for making Terraform resources and remade the schema based on some work

---

pipeline/gog_pipeline/gog_lambda_extract.py
pipeline/gog_pipeline/gog_load.py
pipeline/gog_pipeline/gog_load_functions.py
pipeline/gog_pipeline/gog_pipeline.py
pipeline/steam_pipeline/steam_lambda_extract.py
pipeline/steam_pipeline/steam_load.py
pipeline/steam_pipeline/steam_load_functions.py
pipeline/steam_pipeline/steam_pipeline.py

Updated the load function so that release date is related to platform assignment not game.

Rob updated load to be inline with the new schema

---

dashboard/components.py
dashboard/dashboard.py
dashboard/main.py
dashboard/requirements.txt

Closes #89 
- Adds to dashboard.py a basic board that conforms to the dashboard wireframe

Candice - Merge basic dashboard frame

---

pipeline/gog_pipeline/gog_transform.py
pipeline/gog_pipeline/test_gog_transform.py

- Fixes price = None issue
- Fixes image formatting
As requested.
Closes #114

Candice - Merging more transform bugfixes

---

pipeline/epic_pipeline/epic_extract.py
pipeline/epic_pipeline/get_rating.gql
pipeline/epic_pipeline/query_all.gql
pipeline/epic_pipeline/test_epic_extract.py

I've formatted data extracted from GraphQL api in the same format as we've done in the previous ETL pipelines. needs transform and load scripts.
Then should close #39

EPIC extraction finished

---

dashboard/pages/Developers.py
dashboard/requirements.txt
test_terraform/etl_pipeline.tf

I have completed the dashboard code inside of Streamlit to make a dashboard for Developers to match with our second stakeholder Miranda and includes visualisations that they may want to see such as:
- The Top 10 Best Reviewed Games in the System
- Best Reviewed Games (can be filtered by genre, tag, price or platform)
- A scattergraph showcasing the Price of a game against its rating to make some thoughts from
Also, I have made the Terraform code run for both the Steam and GOG pipelines to run on the Cloud every three hours as requested.
Closes tickets #59, #96 and #111

Completed a Dashboard script for Developers with useful visualisations

---

pipeline/epic_pipeline/epic_transform.py
pipeline/epic_pipeline/test_epic_transform.py

Closes #54 
- Adds epic transform script
- Adds a testing suite for that script
Thats it! Should be okay, let me know if you spot something to change.

Candice - Finished epic transform

---

pipeline/epic_pipeline/epic_extract.py
pipeline/epic_pipeline/epic_pipeline.py
pipeline/gog_pipeline/gog_pipeline.py
pipeline/steam_pipeline/steam_pipeline.py
pipeline/steam_pipeline/test_steam_extract.py

I have updated the pipeline scripts to include nsfw. Previously all were set to true because we had not added a check for it.
Closes #130 
Also edited the epic extract to improve pylint.

Rob pipeline

---

pipeline/epic_pipeline/epic_transform.py
pipeline/gog_pipeline/test_gog_transform.py

Fixes epic transform "score is a string" bug.
Thats it!

Candice - epic transform bug fix

---

pipeline/gog_pipeline/test_gog_extract.py

Working on #75 
- Adds two new tests to test_gog_extract.py increasing coverage by 15%.
Shelving more tests for now as more important stuff to work on.

Candice - merge new gog_extract tests

---

dashboard/dashboard.py
dashboard/pages/Developers.py
dashboard/pages/game.py
dashboard/pages/game_developer.py
dashboard/pages/game_publisher.py
dashboard/pages/platform.py
database/schema.sql
terraform/weekly_email_summary.tf

I have completed some changes to the dashboard so that all filters now work and I have made the pages for Game Developer, Publisher and the Game work but not yet for platform.

Completed dashboard changes for everything but platform

---

email_lambdas/genre_emails/genre_emails_ECR.sh
email_lambdas/weekly-digest/weekly_digest_ECR.sh
terraform/daily_email_summary.tf
terraform/variables.tf
terraform/weekly_email_summary.tf

Closes #157 #159 
- Adds lambda terraforming for the emailing code
- Added ECR push files to the emails
@robkenhow77-sigma-labs-trainee Could you adapt the workflows to push these docker images too please!

Candice - Added email lambda terraform + dockerpush files

---

pipeline/epic_pipeline/epic_extract.py
pipeline/epic_pipeline/epic_transform.py

Solves issue #162 
If we can't get the pageSlug from the graphQL then it will go into the db as N/A

Stronger against None types in EPIC for pageSlug

---

pipeline/epic_pipeline/epic_load.py
pipeline/epic_pipeline/epic_load_functions.py
pipeline/epic_pipeline/epic_pipeline.py
pipeline/epic_pipeline/test_epic_load_functions.py
pipeline/gog_pipeline/gog_load.py
pipeline/gog_pipeline/gog_load_functions.py
pipeline/gog_pipeline/gog_pipeline.py
pipeline/gog_pipeline/test_gog_load_functions.py
pipeline/steam_pipeline/steam_load.py
pipeline/steam_pipeline/steam_load_functions.py
pipeline/steam_pipeline/steam_pipeline.py
pipeline/steam_pipeline/test_steam_load_functions.py

I have added the hyperlink database column that allows us to go the the game on the platform via the dashboard.
Closes #146

Added the hyperlink database column to loading 

---

email_lambdas/genre_emails/genre_emails_ECR.sh
email_lambdas/weekly-digest/requirements.txt
email_lambdas/weekly-digest/weekly_digest_ECR.sh

Candice - Merging new dockerpush files

---

email_lambdas/weekly-digest/requirements.txt
email_lambdas/weekly-digest/weekly_digest.py

fixed score problem with weekly email

---

pipeline/steam_pipeline/steam_pipeline.py
pipeline/steam_pipeline/steam_transform.py

- Updated code to stop the timedelta type wrong error

Candice - Pipeline bugfix

---

dashboard/components.py
dashboard/data_source.py
dashboard/main.py
dashboard/pages/subscribe.py
dashboard/requirements.txt

Fixed a bug where error is thrown when a user tries to subscribe to a genre that has no subscribers. Closes #183 
Fixed a bug where a user can subscribe to the same genre multiple times. Closes #181 
Restyled the subscription page to match the rest of the dashboard theme. Closes #180

Subscribe page bug fixes and restyling

---

email_lambdas/weekly-digest/weekly_digest.py

Closes #173 
- No longer breaks weekly email lambda
- Fixed pdf saving directory.
- Slightly refactored function to be less lines of code

weekly email now works assuming SES works :)

---

dashboard/Dockerfile

I have changed the dockerfile so it runs on the service.
Closes #200

 sorted out the dockerfile for the dashboard

---

.github/workflows/weekly_email.yml
email_lambdas/genre_emails/requirements.txt

Update weekly digest workflow to point to correct weekly digest file to push the ecr successfully. Closes #207

Update weekly digest workflow
